Allow use of StringMap for Context
nadako/hxmustache pull request #9
Opened 2020-02-23 20:02 UTC by Tezar

resolves #8

2020-02-23 20:05 UTC, nadako requested changes

2020-02-23 20:05 UTC, nadako commented on src/mustache/Context.hx
> +        var value;
No need to declare this var, just move the whole `var value = Reflect.field(object, name)` expression after the check

2020-02-23 20:05 UTC, nadako commented on src/mustache/Context.hx
> +        if (Std.is(object, haxe.ds.StringMap)) {
`Std.downcast` will do the type check, so there's no need for `Std.is` here, simply do
```haxe
var map = Std.downcast(object, haxe.ds.StringMap);
if (map != null) {
    return map.exists(name) ? Some(map.get(name)) : None;
}
```

2020-02-23 20:19 UTC, Tezar commented
Looking at travis, should I bump haxe version to 4.0.1?

2020-02-23 20:30 UTC, nadako commented
Hmm, maybe better do `#if haxe4 Std.downcast #else Std.instance #end(object, haxe.ds.StringMap)` or something for now, because it's the only thing that requires Haxe 4, right?

2020-02-23 20:47 UTC, Tezar commented
Reread why downcast was introduced and seems ok to use instance on hx3. Patched as suggested.

Build still fails but that's due to problem with buddy tools.

2020-02-23 21:38 UTC, merged

2020-02-23 21:38 UTC, nadako commented
Oh well, still merged

2020-02-24 09:42 UTC, Tezar commented
Could I bother you some more with new release to haxe lib? :)

Thanks